### ISSUE TITLE
No dynamoDB table is created after deployment. 

### ISSUE THREAD

**Issue by mvaneijgen** [tmaximini/graphql-apollo-serverless-example#3]
After deployment I get an url which I than add to GraphiQL and when doing a simple query 

```
{
  product {
		id
  }
}
```

or 

```
mutation {
  product(name: "Billy", brand: "Crash") {
    id
  }
}
```

I get 

```{"errors":[{"message":"Schema is not configured for mutations.","locations":[{"line":1,"column":1}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Schema is not configured for mutations.","    at getOperationRootType (/var/task/node_modules/graphql/utilities/getOperationRootType.js:28:13)","    at executeOperation (/var/task/node_modules/graphql/execution/execute.js:210:61)","    at executeImpl (/var/task/node_modules/graphql/execution/execute.js:104:14)","    at Object.execute (/var/task/node_modules/graphql/execution/execute.js:64:35)","    at /var/task/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","    at Generator.next (<anonymous>)","    at /var/task/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/var/task/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","    at execute (/var/task/node_modules/apollo-server-core/dist/requestPipeline.js:228:20)"]}}}]}
```

And when I check the AWS console of DynamoDB there is no database table. I've checked `eu-central-1` and all other regions, but there is nothing created. I can see a S3 bucket and a Lamda function, but the database is nowhere to be found.

**Comment by tmaximini** [comment]
fixed by #5 
This example was built upon a table I previously created but I updated the serverless.yml now to create a table on stack creation. Thanks for pointing that out.
